### ISSUE TITLE
Unused class names in minimal templates

### ISSUE THREAD

**Issue by chrissantamaria** [iansu/cra-minimal-templates#1]
Hi 👋 this is a super cool project - will definitely use in my future CRA apps!

This is a bit of a minor note, but I don't think the class names set on the minimal templates offer anything given that there's no accompanying CSS. Would it be better to just omit them? If so, the starter would look like:

```js
import React from 'react';

function App() {
  return (
    <div style={{ textAlign: 'center' }}>
      <header>
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

Happy to make a PR for `cra-template-minimal` and `cra-template-minimal-typescript` if you'd like to go with this.

**Comment by iansu** [comment]
Good catch. I just copied these templates from Create React App and removed what I could but I missed the class names. I'd be happy to accept a PR to remove them!
